# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpoint',
            name='name',
            field=models.CharField(help_text='Name for the tour point', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tourpoint',
            name='owner',
            field=models.ForeignKey(help_text='Who created this tour point.', on_delete=django.db.models.deletion.CASCADE, related_name='tourpoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
