version: '3'
services:
  db:
    image: postgres:latest
    expose: 
      - 5432
    volumes:
      - "/var/lib/postgresql/data"
    environment: 
      POSTGRES_USER: snowman
      POSTGRES_PASSWORD: Q4mAELAAw1BhZA==
  search:
    image: elasticsearch:2.4
  web:
    build: .
    command: bash -c "pip install -U pip && pip install -Ur requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - "/var/www/snowman.com/static/"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - search
    links:
      - db
      - search