version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/var/www/snowman.com/static/
      - ./snowman.template:/etc/nginx/conf.d/snowman.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/snowman.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - web
    depends_on: 
      - web
  db:
    image: postgres:latest
    restart: always
    expose: 
      - 5432
    volumes:
      - "/var/lib/postgresql/data"
    environment: 
      POSTGRES_USER: snowman
      POSTGRES_PASSWORD: Q4mAELAAw1BhZA==
  search:
    image: elasticsearch:2.4
    restart: always
  cache:
    image: memcached:latest
    restart: always
  management:
    build: .
    depends_on:
      - db
      - search
    links:
      - db
      - search
    volumes:
      - .:/usr/src/app
    command: bash -c "sleep 10 && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata fixtures/fixtures.json && python manage.py rebuild_index --noinput"
  web:
    restart: always
    build: .
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db
      - search
      - cache
      - management
    links:
      - db
      - search
      - cache
      - management
      
volumes:
  static: