version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/var/www/snowman.com/static/
      - ./snowman.template:/etc/nginx/conf.d/snowman.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/snowman.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - web
    depends_on: 
      - web
  db:
    image: postgres:latest
    restart: always
    expose: 
      - 5432
    volumes:
      - "/var/lib/postgresql/data"
    environment: 
      POSTGRES_USER: snowman
      POSTGRES_PASSWORD: Q4mAELAAw1BhZA==
  search:
    image: elasticsearch:2.4
    restart: always
  cache:
    image: memcached:latest
    restart: always
  web:
    restart: always
    build: .
    command: bash -c "pip install -U pip && pip install -Ur requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && uwsgi --ini uwsgi.ini"
    volumes:
      - .:/code
      - static:/var/www/snowman.com/static/
    expose:
      - 8000
    depends_on:
      - db
      - search
      - cache
    links:
      - db
      - search
      - cache
      
volumes:
  static: